version: '3.1'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5555:80"
        volumes:
            - ./html:/var/www/html
            - ./vendor:/var/www/vendor

    db:
        image: mariadb
        command: --init-file /data/application/init.sql
        volumes:
            - ./database:/var/lib/mysql
            - ./init.sql:/data/application/init.sql
        environment:
            MYSQL_ROOT_PASSWORD: example

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
