CREATE DATABASE IF NOT EXISTS web_db;
use web_db;
CREATE TABLE IF NOT EXISTS users
(
    `U_ID`         INT          NOT NULL AUTO_INCREMENT,
    `U_FIRST_NAME` VARCHAR(255) NOT NULL,
    `U_LAST_NAME`  VARCHAR(255) NOT NULL,
    `U_EMAIL`      VARCHAR(255) NOT NULL,
    `U_PASSWORD`   VARCHAR(255) NOT NULL,
    `U_IS_ADMIN`   TINYINT(1)   NOT NULL,
    PRIMARY KEY (`U_ID`)
) ENGINE = InnoDB;