CREATE DATABASE IF NOT EXISTS web_db;
use web_db;

CREATE TABLE IF NOT EXISTS users
(
    `U_ID`         INT          NOT NULL AUTO_INCREMENT,
    `U_FIRST_NAME` VARCHAR(255) NOT NULL,
    `U_LAST_NAME`  VARCHAR(255) NOT NULL,
    `U_EMAIL`      VARCHAR(255) NOT NULL,
    `U_PASSWORD`   VARCHAR(255) NOT NULL,
    `U_IS_ADMIN`   TINYINT(1)   NOT NULL,
    PRIMARY KEY (`U_ID`)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `posts`
(
    `PO_ID`           INT          NOT NULL AUTO_INCREMENT,
    `PO_TITLE`        VARCHAR(255) NOT NULL,
    `PO_AUTHOR_ID`    INT          NOT NULL,
    `PO_CONTENT`      TEXT         NOT NULL,
    `PO_PUBLISH_DATE` DATE         NOT NULL,
    PRIMARY KEY (`PO_ID`)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `post_comment`
(
    `POC_ID`           INT  NOT NULL AUTO_INCREMENT,
    `POC_AUTHOR_ID`    INT  NOT NULL,
    `POC_COMMENT`      TEXT NOT NULL,
    `POC_PUBLISH_DATE` DATE NOT NULL,
    PRIMARY KEY (`POC_ID`)
) ENGINE = InnoDB;